-- fluid.pdf_uploads definition

CREATE TABLE `pdf_uploads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_amount` varchar(255) DEFAULT NULL,
  `paid_amount` varchar(255) DEFAULT NULL,
  `paid_detail` text,
  `order_id` varchar(255) CHARACTER SET utf8 NOT NULL,
  `is_paid` tinyint(1) NOT NULL DEFAULT '0',
  `path` varchar(255) CHARACTER SET utf8 NOT NULL,
  `invoice_date` date DEFAULT NULL,
  `hash` varchar(255) CHARACTER SET utf8 NOT NULL,
  `size` int(11) NOT NULL,
  `entity` tinyint(1) NOT NULL,
  `client_id` varchar(36) DEFAULT NULL COMMENT 'Уникальный идентификатор',
  `client_code` varchar(11) DEFAULT NULL COMMENT 'Код контрагента',
  `generated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `visited` timestamp NULL DEFAULT NULL,
  `lastAction` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `views` int(100) NOT NULL DEFAULT '0',
  `unzip` tinyint(1) NOT NULL DEFAULT '0',
  `pay_block` tinyint(1) NOT NULL,
  `pay_link` varchar(255) NOT NULL,
  `InvoiceId` int(11) NOT NULL,
  `paid_percent` varchar(255) DEFAULT NULL,
  `paid_date` timestamp NULL DEFAULT NULL,
  `contract_date` timestamp NULL DEFAULT NULL,
  `position` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `director` varchar(255) DEFAULT NULL,
  `accountant` varchar(255) DEFAULT NULL,
  `email_hash` varchar(32) NOT NULL,
  `link` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=28125 DEFAULT CHARSET=cp1251;